# Generated by Django 3.2.10 on 2023-09-23 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_rename_heihgt_imagesize_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.CreateModel(
            name='ImageThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('date_of_used', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.imagesize')),
            ],
        ),
    ]
